eval.batch_size: 2
eval.cutoff_len: 1024
eval.dataset:
- original_model_real_val
eval.dataset_dir: LLaMA-Factory/data
eval.max_new_tokens: 512
eval.max_samples: '100000'
eval.output_dir: original_real_eval_2025-10-22-18-55-23
eval.predict: true
eval.temperature: 0.95
eval.top_p: 0.7
top.booster: auto
top.checkpoint_path: []
top.finetuning_type: lora
top.model_name: Llama-3.2-3B-Instruct
top.quantization_bit: none
top.quantization_method: bnb
top.rope_scaling: none
top.template: llama3
