adapter_name_or_path: saves/Qwen2.5-Omni-3B/lora/real_train_2025-08-19-13-52-49
cutoff_len: 1024
dataset_dir: LLaMA-Factory/data
ddp_timeout: 180000000
do_predict: true
eval_dataset: real_val
finetuning_type: lora
flash_attn: auto
max_new_tokens: 1024
max_samples: 100000
model_name_or_path: /home/ub/wohen/test/models/Qwen2.5-Omni-3B
output_dir: saves/Qwen2.5-Omni-3B/lora/real_eval_2025-09-03-19-57-10
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bnb
report_to: none
stage: sft
temperature: 0.95
template: qwen2_omni
top_p: 0.7
trust_remote_code: true
