adapter_name_or_path: saves/Qwen2.5-Omni-3B/lora/train_2025-07-02-10-59-32
cutoff_len: 1024
dataset_dir: LLaMA-Factory/data
ddp_timeout: 180000000
do_predict: true
eval_dataset: virtual_val
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 100000
model_name_or_path: /home/ub/wohen/test/Qwen2.5-Omni-3B
output_dir: saves/Qwen2.5-Omni-3B/lora/eval_2025-07-08-17-24-49
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bnb
report_to: none
stage: sft
temperature: 0.95
template: qwen2_omni
top_p: 0.7
trust_remote_code: true
